### ISSUE TITLE
Debug server not connecting

### ISSUE THREAD

**Issue by rattrapper** [LockBlock-dev/wot-mods#1]
Hi, I know that this project wasn't updated for a long time but is there any change you might know why I can't connect client with the server? I followed the tutorial, packed and added the mod, but there's no [Debug-Server] entries in the python.log file and no output in the running client when I start the game. Are there any other ways to troubleshoot? It's my first time trying to develop a mod for WoT and I was hoping to get to know the API using your debugging server. Thanks!

**Comment by LockBlock-dev** [comment]
Hey, I have installed World of Tanks (latest 1.23.1.0) to test and got everything running without any issue. Reminder, you must run the python client before starting your game.

console output:  
![image](https://github.com/LockBlock-dev/wot-mods/assets/68129141/f247d506-a47f-4bd8-aa72-e5dc60567804)

python.log output:  
![image](https://github.com/LockBlock-dev/wot-mods/assets/68129141/a164c04f-c6db-422a-8d73-a94267a3f7f1)
